server.servlet.context-path=/company-core/
server.port=9908
server.shutdown=graceful

LOG_PATH=/home/opc/log
logging.file.name=api.txt

##############################################################################
logging.level.com.lti=info

######################### Local #################################
# H2 Config
#spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=default
#spring.datasource.password=default
#
## JPA
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
## H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Flyway
spring.flyway.enabled=true


spring.datasource.url=jdbc:oracle:thin:@database1_high?TNS_ADMIN=/home/opc
spring.datasource.username=ADMIN
spring.datasource.password=Password@123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.default_schema=ADMIN

spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true


spring.security.user.name=admin
spring.security.user.password=admin


spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.keepalive-time=1200000


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE 

#JPA properties
spring.jpa.show-sql = true

#the below are the default values
#hibernate.hbm2ddl.auto = none
#spring.jpa.properties.hibernate.hbm2ddl.auto=none
spring.jpa.hibernate.ddl-auto = none

spring.main.allow-bean-definition-overriding=true

#spring.flyway.enabled=true
springdoc.version=1.0

#springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.path=/swagger-ui-custom.html
#springdoc.version=1.0

maxPoolSize=200
minPoolSize=1
tenantId=TSTTESTDB
url=jdbc:oracle:thin:@database1_high?TNS_ADMIN=/home/opc
dbUserName=ADMIN
dbPassword=Password@123
driverClassName=oracle.jdbc.OracleDriver

spring.main.allow-circular-references=true
#spring.security.oauth2.resourceserver.jwt.public-key-location=file:/opt/ReferenceData/SQA2/springboot/config/accounts-sqa1.fst.lntinfotech.com.pub

management.endpoint.health.enabled=true
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health
management.endpoints.jmx.exposure.include=health
management.endpoint.health.show-details=never
management.security.enabled=true
