-- ============================
-- address TABLE
-- One-to-One with Project
-- ============================
CREATE TABLE IF NOT EXISTS address (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_type VARCHAR(30) NOT NULL,
    address_line1 VARCHAR(150) NOT NULL,
    address_line2 VARCHAR(150),
    city VARCHAR(80) NOT NULL,
    thaluk VARCHAR(80),
    state VARCHAR(80) NOT NULL,
    country VARCHAR(80) NOT NULL,
    pincode VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- ============================
-- EMPLOYEE TABLE
-- ============================
CREATE TABLE IF NOT EXISTS employee (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    level VARCHAR(2) NOT NULL,
    address_id BIGINT,
    primary_phone_number BIGINT NOT NULL,
    secondary_phone_number BIGINT,
    date_of_joining DATE NOT NULL,
    date_of_resign DATE,
    status VARCHAR(10),
    email VARCHAR(50) UNIQUE,
    
     CONSTRAINT fk_employee_address
        FOREIGN KEY (address_id)
        REFERENCES address(address_id)
        ON DELETE SET NULL
);

-- ============================
-- SALARY TABLE
-- One-to-One with EMPLOYEE
-- ============================
CREATE TABLE IF NOT EXISTS salary (
    employee_id BIGINT PRIMARY KEY,
    level VARCHAR(2) NOT NULL,
    salary_per_hour NUMERIC(10,2) NOT NULL,

    CONSTRAINT fk_salary_employee
        FOREIGN KEY (employee_id)
        REFERENCES employee(employee_id)
        ON DELETE CASCADE
);

-- ============================
-- project TABLE
-- One-to-One with Address
-- ============================
CREATE TABLE IF NOT EXISTS project (
    project_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code VARCHAR(20) UNIQUE NOT NULL,
    project_name VARCHAR(100) NOT NULL,
    address_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_project_address
        FOREIGN KEY (address_id)
        REFERENCES address(address_id)
        ON DELETE SET NULL
); 
-- ============================
-- ATTENDANCE TABLE
-- One-to-Many with EMPLOYEE
-- ============================
CREATE TABLE IF NOT EXISTS attendance (
	attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    date DATE NOT NULL,
    days NUMERIC(10,2) NOT NULL,

    CONSTRAINT uq_attendance
        UNIQUE (employee_id, project_id, date),

    CONSTRAINT fk_attendance_employee
        FOREIGN KEY (employee_id)
        REFERENCES employee(employee_id)
        ON DELETE CASCADE,
        
    CONSTRAINT fk_attendance_project
        FOREIGN KEY (project_id)
        REFERENCES project(project_id)
        ON DELETE CASCADE    
);

CREATE INDEX IF NOT EXISTS idx_attendance_employee_id
ON attendance(employee_id);
