<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.company.core</groupId>
		<artifactId>CompanyCoreModule</artifactId>
		<version>1.0</version>
		<relativePath>../pom.xml</relativePath> 
	</parent>
	<artifactId>CompanyProcessModule</artifactId>
	<name>CompanyProcessModule</name>
	<description>Company Process API</description>

	<dependencies>
		<dependency>
			<groupId>com.company.core</groupId>
			<artifactId>CompanyPayrollModule</artifactId>
			<version>${project.version}</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<includeSystemScope>true</includeSystemScope>
				</configuration>
			</plugin>

		</plugins>
	</build>

</project>